import * as XLSX from 'xlsx';
import {
  ParsedWorkbook,
  CourseFileParsed,
  PasswordFileParsed,
  SectionMeta,
  CourseColumn,
  CourseStudent,
  CourseInsightsAggregate,
  SectionData,
  StudentCourseValue,
} from '../../../types/course';

const COMPLETE_THRESHOLD = 99.5;

export function parseCell(raw: unknown): StudentCourseValue {
  if (raw === null || raw === undefined || raw === '') return { value: 0, notStarted: true };
  if (typeof raw === 'number') return { value: raw, notStarted: raw <= 0 };
  const str = String(raw);
  const match = str.match(/-?\d+(\.\d+)?/);
  const num = match ? parseFloat(match[0]) : 0;
  const notStarted = /not started/i.test(str) || num <= 0;
  return { value: num, notStarted };
}

export function parseSectionMeta(groupStr: string | null | undefined, fileName: string): SectionMeta {
  const source = (groupStr && String(groupStr).trim()) || fileName;
  const m = String(source).match(/(\d{4}-\d{4})-([A-Za-z]+)-([A-Za-z0-9]+)/);
  if (m) {
    return {
      batch: m[1],
      branch: m[2].toUpperCase(),
      section: m[3].toUpperCase(),
      label: `${m[2].toUpperCase()}-${m[3].toUpperCase()}`,
    };
  }
  return { batch: '—', branch: 'General', section: source, label: source };
}

export function shortCourseLabel(header: string): string {
  const h = String(header).replace(/\s*\(%\)\s*$/i, '').trim();
  const parts = h.split(' - ');
  return parts[0].trim();
}

export function courseCode(header: string): string {
  const h = String(header).replace(/\s*\(%\)\s*$/i, '').trim();
  const parts = h.split(' - ');
  return parts.length > 1 ? parts[1].trim() : '';
}

function isFooterRow(row: unknown[]): boolean {
  return row.some((c) => typeof c === 'string' && /generated by/i.test(c));
}

export async function parseCourseWorkbook(file: File): Promise<ParsedWorkbook> {
  const buf = await file.arrayBuffer();
  const wb = XLSX.read(buf, { type: 'array' });
  const ws = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json<unknown[]>(ws, { header: 1, defval: null, blankrows: false });
  if (!rows.length) throw new Error(`"${file.name}" is an empty sheet.`);

  const header = (rows[0] as unknown[]).map((h) => (h === null || h === undefined ? '' : String(h).trim()));
  const body = (rows.slice(1) as unknown[][]).filter(
    (r) => r && r.length && !isFooterRow(r) && r[0] !== null && r[1] !== null
  );

  // Check for Password Not Set report
  if (header.includes('Created Time')) {
    const nameIdx = header.indexOf('Name');
    const emailIdx = header.indexOf('Email');
    const groupIdx = header.indexOf('Groups');
    const timeIdx = header.indexOf('Created Time');

    const entries = body.map((r) => ({
      name: String(r[nameIdx] ?? ''),
      email: String(r[emailIdx] ?? ''),
      groups: String(r[groupIdx] ?? ''),
      createdTime: timeIdx >= 0 ? String(r[timeIdx] ?? '') : '',
    }));

    const meta = parseSectionMeta(entries[0]?.groups, file.name);
    return { kind: 'password', fileName: file.name, meta, entries };
  }

  // Check for Group-wise course progress report
  if (header.includes('Member Id') || header.includes('Groups')) {
    const idIdx = header.indexOf('Member Id');
    const nameIdx = header.indexOf('Name');
    const emailIdx = header.indexOf('Email');
    const groupIdx = header.indexOf('Groups');

    const courseIdxs = header
      .map((h, i) => ({ h, i }))
      .filter(({ h, i }) => i > groupIdx && h && h !== '');

    const courses: CourseColumn[] = courseIdxs.map(({ h }) => ({
      key: h,
      label: shortCourseLabel(h),
      code: courseCode(h),
    }));

    const students: CourseStudent[] = body.map((r) => {
      const courseValues: Record<string, StudentCourseValue> = {};
      let sum = 0;
      courseIdxs.forEach(({ h, i }) => {
        const { value, notStarted } = parseCell(r[i]);
        courseValues[h] = { value, notStarted };
        sum += value;
      });
      const avg = courseIdxs.length ? sum / courseIdxs.length : 0;
      return {
        id: idIdx >= 0 ? String(r[idIdx] ?? '') : '',
        name: nameIdx >= 0 ? String(r[nameIdx] ?? '') : '',
        email: emailIdx >= 0 ? String(r[emailIdx] ?? '') : '',
        groups: groupIdx >= 0 ? String(r[groupIdx] ?? '') : '',
        courseValues,
        avg,
      };
    });

    const meta = parseSectionMeta(students[0]?.groups, file.name);
    return { kind: 'course', fileName: file.name, meta, courses, students };
  }

  throw new Error(
    `"${file.name}" has unrecognized columns. Expected a group-wise course progress report or password-not-set export.`
  );
}

export function aggregateCourseInsights(
  courseFiles: CourseFileParsed[],
  passwordFiles: PasswordFileParsed[],
  threshold = 40,
  avgMax = 70,
  goodMax = 90
): CourseInsightsAggregate | null {
  if (!courseFiles.length) return null;

  // Group by student's own Groups value so combined or single sheets both resolve correctly
  const sectionMap = new Map<
    string,
    SectionMeta & {
      fileNames: Set<string>;
      courseMap: Map<string, CourseColumn>;
      students: CourseStudent[];
    }
  >();

  courseFiles.forEach((f) => {
    f.students.forEach((st) => {
      const rawGroup = (st.groups && String(st.groups).trim()) || '';
      const meta = parseSectionMeta(rawGroup, f.fileName);
      const key = meta.label;
      if (!sectionMap.has(key)) {
        sectionMap.set(key, { ...meta, fileNames: new Set(), courseMap: new Map(), students: [] });
      }
      const entry = sectionMap.get(key)!;
      entry.fileNames.add(f.fileName);
      f.courses.forEach((c) => {
        if (!entry.courseMap.has(c.key)) entry.courseMap.set(c.key, c);
      });
      entry.students.push(st);
    });
  });

  const sections: SectionData[] = Array.from(sectionMap.values())
    .map((sec) => {
      const courses = Array.from(sec.courseMap.values());
      const studentCount = sec.students.length;
      const avgOfAvgs = studentCount
        ? sec.students.reduce((s, st) => s + st.avg, 0) / studentCount
        : 0;

      const perCourse = courses.map((c) => {
        let sum = 0;
        let notStartedCount = 0;
        let completeCount = 0;
        let seen = 0;

        sec.students.forEach((st) => {
          const cv = st.courseValues[c.key];
          if (!cv) return;
          seen++;
          sum += cv.value;
          if (cv.notStarted) notStartedCount++;
          if (cv.value >= COMPLETE_THRESHOLD) completeCount++;
        });

        return {
          ...c,
          avg: seen ? sum / seen : 0,
          notStartedCount,
          completeCount,
          notStartedRate: seen ? notStartedCount / seen : 0,
        };
      });

      const atRisk = sec.students.filter((s) => s.avg < threshold);
      const startedCount = sec.students.filter((s) =>
        Object.values(s.courseValues).some((cv) => !cv.notStarted)
      ).length;
      const notStartedCount = studentCount - startedCount;

      return {
        batch: sec.batch,
        branch: sec.branch,
        section: sec.section,
        label: sec.label,
        fileName: Array.from(sec.fileNames).join(', '),
        studentCount,
        avgOfAvgs,
        perCourse,
        atRisk,
        startedCount,
        notStartedCount,
        students: sec.students,
        courses,
      };
    })
    .sort((a, b) => a.label.localeCompare(b.label));

  const totalStudents = sections.reduce((s, sec) => s + sec.studentCount, 0);
  const overallAvg = totalStudents
    ? sections.reduce((s, sec) => s + sec.avgOfAvgs * sec.studentCount, 0) / totalStudents
    : 0;
  const totalAtRisk = sections.reduce((s, sec) => s + sec.atRisk.length, 0);

  // Group password issues by section label
  const pwBySection: Record<string, { meta: SectionMeta; entries: PasswordFileParsed['entries'] }> = {};
  passwordFiles.forEach((f) => {
    f.entries.forEach((entry) => {
      const rawGroup = (entry.groups && String(entry.groups).trim()) || '';
      const meta = parseSectionMeta(rawGroup, f.fileName);
      const key = meta.label;
      if (!pwBySection[key]) pwBySection[key] = { meta, entries: [] };
      pwBySection[key].entries.push(entry);
    });
  });
  const totalPasswordIssues = Object.values(pwBySection).reduce((s, g) => s + g.entries.length, 0);

  // Enrollment and activation summary
  const enrollment = sections.map((sec) => {
    const passwordNotSet = pwBySection[sec.label]?.entries.length || 0;
    return {
      label: sec.label,
      started: sec.startedCount,
      notStarted: sec.notStartedCount,
      passwordNotSet,
      subTotal: sec.studentCount + passwordNotSet,
    };
  });

  const enrollmentTotals = enrollment.reduce(
    (acc, r) => ({
      started: acc.started + r.started,
      notStarted: acc.notStarted + r.notStarted,
      passwordNotSet: acc.passwordNotSet + r.passwordNotSet,
      subTotal: acc.subTotal + r.subTotal,
    }),
    { started: 0, notStarted: 0, passwordNotSet: 0, subTotal: 0 }
  );

  // Branch grouping for course comparison
  const branches: Record<
    string,
    {
      sections: SectionData[];
      courseAgg: Map<
        string,
        { label: string; code: string; sumPct: number; students: number; notStarted: number }
      >;
    }
  > = {};

  sections.forEach((sec) => {
    if (!branches[sec.branch]) branches[sec.branch] = { sections: [], courseAgg: new Map() };
    branches[sec.branch].sections.push(sec);
    sec.perCourse.forEach((c) => {
      const agg = branches[sec.branch].courseAgg.get(c.key) || {
        label: c.label,
        code: c.code,
        sumPct: 0,
        students: 0,
        notStarted: 0,
      };
      agg.sumPct += c.avg * sec.studentCount;
      agg.students += sec.studentCount;
      agg.notStarted += c.notStartedCount;
      branches[sec.branch].courseAgg.set(c.key, agg);
    });
  });

  const branchCharts = Object.entries(branches).map(([branch, data]) => ({
    branch,
    courses: Array.from(data.courseAgg.values()).map((c) => ({
      key: c.label,
      label: c.label,
      code: c.code,
      avg: c.students ? c.sumPct / c.students : 0,
      notStartedRate: c.students ? c.notStarted / c.students : 0,
      students: c.students,
    })),
  }));

  // Flatten all students
  const allStudentsFlat: CourseStudent[] = sections.flatMap((sec) =>
    sec.students.map((s) => ({
      ...s,
      sectionLabel: sec.label,
      notStartedCourses: sec.courses
        .filter((c) => s.courseValues[c.key] && s.courseValues[c.key].notStarted)
        .map((c) => c.label),
    }))
  );

  // Performance categories
  const b1 = threshold;
  const b2 = Math.max(avgMax, b1);
  const b3 = Math.max(goodMax, b2);

  const categoryDefs = [
    {
      key: 'atRisk' as const,
      title: 'At Risk',
      range: `below ${b1}%`,
      color: '#C4472D',
      test: (avg: number) => avg < b1,
    },
    {
      key: 'average' as const,
      title: 'Average',
      range: `${b1}%–${(b2 - 0.1).toFixed(1)}%`,
      color: '#B8860F',
      test: (avg: number) => avg >= b1 && avg < b2,
    },
    {
      key: 'good' as const,
      title: 'Good',
      range: `${b2}%–${(b3 - 0.1).toFixed(1)}%`,
      color: '#2E4269',
      test: (avg: number) => avg >= b2 && avg < b3,
    },
    {
      key: 'excellent' as const,
      title: 'Excellent',
      range: `${b3}% and above`,
      color: '#0E7C66',
      test: (avg: number) => avg >= b3,
    },
  ];

  const categorizedStudents = categoryDefs.map((c) => ({
    ...c,
    students: allStudentsFlat.filter((s) => c.test(s.avg)).sort((a, b) => a.avg - b.avg),
  }));

  const atRiskAll = categorizedStudents[0].students;
  const topPerformers = [...allStudentsFlat].sort((a, b) => b.avg - a.avg).slice(0, 10);

  const sortedByAvg = [...sections].sort((a, b) => a.avgOfAvgs - b.avgOfAvgs);
  const weakestSection = sortedByAvg[0] || null;
  const strongestSection = sortedByAvg[sortedByAvg.length - 1] || null;

  let weakestCourse: { label: string; code: string; notStartedRate: number; branch: string } | null = null;
  branchCharts.forEach((b) => {
    b.courses.forEach((c) => {
      if (!weakestCourse || c.notStartedRate > weakestCourse.notStartedRate) {
        weakestCourse = { ...c, branch: b.branch };
      }
    });
  });

  const batches = Array.from(new Set(sections.map((s) => s.batch))).filter((b) => b !== '—');

  return {
    sections,
    totalStudents,
    overallAvg,
    totalAtRisk,
    pwBySection,
    totalPasswordIssues,
    branchCharts,
    allStudentsFlat,
    categorizedStudents,
    atRiskAll,
    topPerformers,
    weakestSection,
    strongestSection,
    weakestCourse,
    batches,
    enrollment,
    enrollmentTotals,
  };
}
